// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 22sdoN4aX8y6Pu1pTjChkF
// Component: khFbRdDXz6fylP
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_commerce_storefront.module.css"; // plasmic-import: 22sdoN4aX8y6Pu1pTjChkF/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: khFbRdDXz6fylP/css

import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: ok1rgGDMnRa3OM/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: 7GnShiXH8Pyate/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: SH2PqLiOL45atW/icon

export type PlasmicRating__VariantMembers = {
  rating:
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf";
};

export type PlasmicRating__VariantsArgs = {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
};

type VariantPropType = keyof PlasmicRating__VariantsArgs;
export const PlasmicRating__VariantProps = new Array<VariantPropType>("rating");

export type PlasmicRating__ArgsType = {};
type ArgPropType = keyof PlasmicRating__ArgsType;
export const PlasmicRating__ArgProps = new Array<ArgPropType>();

export type PlasmicRating__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRatingProps {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
  className?: string;
}

function PlasmicRating__RenderFunc(props: {
  variants: PlasmicRating__VariantsArgs;
  args: PlasmicRating__ArgsType;
  overrides: PlasmicRating__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__r2AbW, {
          [sty.svgrating_five__r2AbWbaoQt]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__r2AbWun4C2]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__r2AbWxlHti]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_half__r2AbWhtBEk]: hasVariant(
            variants,
            "rating",
            "half"
          ),
          [sty.svgrating_oneHalf__r2AbWDhzfo]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svgrating_one__r2AbW35Glu]: hasVariant(
            variants,
            "rating",
            "one"
          ),
          [sty.svgrating_threeHalf__r2AbWj8Fv7]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__r2AbWrOv0H]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__r2AbWo5E1T]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svgrating_two__r2AbWsqdjJ]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__bzDp, {
          [sty.svgrating_five__bzDpbaoQt]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__bzDpUn4C2]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__bzDpxlHti]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_oneHalf__bzDpDhzfo]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svgrating_threeHalf__bzDpj8Fv7]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__bzDpROv0H]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__bzDpO5E1T]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svgrating_two__bzDpsqdjJ]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__d04LN, {
          [sty.svgrating_five__d04LNbaoQt]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__d04LNun4C2]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__d04LNxlHti]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_threeHalf__d04LNj8Fv7]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__d04LNrOv0H]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__d04LNo5E1T]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg___3Dije, {
          [sty.svgrating_five___3DijebaoQt]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf___3DijeUn4C2]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four___3DijexlHti]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_threeHalf___3Dijej8Fv7]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__k69B8, {
          [sty.svgrating_five__k69B8BaoQt]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__k69B8Un4C2]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRating__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRating__VariantsArgs;
    args?: PlasmicRating__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRating__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRating__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
