// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 22sdoN4aX8y6Pu1pTjChkF
// Component: nlG4zwvQiCYdkX
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PaheHeaderMenuTextDark from "../../PaheHeaderMenuTextDark"; // plasmic-import: otPdDgODX-n5De/component
import ProductMian from "../../ProductMian"; // plasmic-import: SKEGE57ywhpzqy/component
import ShopingSection from "../../ShopingSection"; // plasmic-import: i0lYnyqtSwaOI9/component
import Instagram from "../../Instagram"; // plasmic-import: SXdIN0VA4a2nJu/component
import Footer from "../../Footer"; // plasmic-import: eZWnvjMgxXz0vo/component

import { useScreenVariants as useScreenVariants_0MRtZvbV1Afi8D } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 0MRtZvbV1AFI8D/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_commerce_storefront.module.css"; // plasmic-import: 22sdoN4aX8y6Pu1pTjChkF/projectcss
import sty from "./PlasmicShop.module.css"; // plasmic-import: nlG4zwvQiCYdkX/css

export type PlasmicShop__VariantMembers = {};

export type PlasmicShop__VariantsArgs = {};
type VariantPropType = keyof PlasmicShop__VariantsArgs;
export const PlasmicShop__VariantProps = new Array<VariantPropType>();

export type PlasmicShop__ArgsType = {};
type ArgPropType = keyof PlasmicShop__ArgsType;
export const PlasmicShop__ArgProps = new Array<ArgPropType>();

export type PlasmicShop__OverridesType = {
  root?: p.Flex<"div">;
  paheHeaderMenuTextDark?: p.Flex<typeof PaheHeaderMenuTextDark>;
  shopingSection?: p.Flex<typeof ShopingSection>;
  instagram?: p.Flex<typeof Instagram>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultShopProps {}

function PlasmicShop__RenderFunc(props: {
  variants: PlasmicShop__VariantsArgs;
  args: PlasmicShop__ArgsType;
  overrides: PlasmicShop__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_0MRtZvbV1Afi8D()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Category"}</title>
        <meta key="og:title" property="og:title" content={"Category"} />
        <meta
          key="description"
          property="og:description"
          name="description"
          content={
            "Inceptos tempor torquent tortor a aptent parturient a a himenaeos in ipsum ad vestibulum euismod ultrices dis vulputate vestibulum non adipiscing."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <PaheHeaderMenuTextDark
            data-plasmic-name={"paheHeaderMenuTextDark"}
            data-plasmic-override={overrides.paheHeaderMenuTextDark}
            className={classNames("__wab_instance", sty.paheHeaderMenuTextDark)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__trk1C)}>
            <div className={classNames(projectcss.all, sty.freeBox__hDl1G)}>
              <div className={classNames(projectcss.all, sty.columns__hi6HG)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__oSdfq)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gXsOx)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__irbwd
                      )}
                    >
                      {"Facial Products"}
                    </h4>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__h7HiI
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/" as const}
                      platform={"nextjs"}
                    >
                      {"Products 3"}
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wwIiH)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__av2Jl
                      )}
                    >
                      {"Hair Products"}
                    </h4>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___57Gyh
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/" as const}
                      platform={"nextjs"}
                    >
                      {"Products 3"}
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pL2E)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4___0SRe1
                      )}
                    >
                      {"Body Products"}
                    </h4>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___3PQti
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/" as const}
                      platform={"nextjs"}
                    >
                      {"Products 3"}
                    </p.PlasmicLink>
                  </p.Stack>
                </p.Stack>

                <div className={classNames(projectcss.all, sty.column__iGtuX)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Jd9O)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__a4LhC
                      )}
                    >
                      {"Facial Products"}
                    </h4>
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__ci2GP)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__o33Iu)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__krOe7
                        )}
                        slot={
                          "A limited-edition, nourishing lip gel to top off your look and feel fantastic."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__mEhob
                            )}
                          >
                            {"$24.00"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__mBbQf)}
                            displayHeight={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? ("320px /* plasmic-token: aNKCpOfwV38Rsi */" as const)
                                : ("320px /* plasmic-token: aNKCpOfwV38Rsi */" as const)
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? ("100%" as const)
                                : ("100%" as const)
                            }
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? ("100%" as const)
                                : ("100%" as const)
                            }
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/cdae2365Eff5A961Dd838B0505A1142B656Efdf95F08C2785B59ALipsjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__szQo
                          )}
                        >
                          {"Lip Fantastic"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__ycWaz)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian___5TLfb
                        )}
                        slot={
                          "Treat your skin with active pore enzymes that replenish sun damaged skin."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__vaXlf
                            )}
                          >
                            {"$ 18.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__u6Vaj)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/c3Cf1B72Aaa232Ba2Ab495Bd7485Efe29Cee138B5F08C2F945173Geljpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__if6Bo
                          )}
                        >
                          {"Eye Purity Gels"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__h0ZeC)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__d3UkQ
                        )}
                        slot={
                          "Anti-aging complexion cream for medium to dry skin. Nourish your face with a natural vitamin burst for that perfectly balanced glow."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__vweiv
                            )}
                          >
                            {"$ 32.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__wjKGv)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/bf9Cf6844F6Febb697Cbba7Dcbbc048Abc6C1Cea5F08C2E616A7CCreamjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___3TTuj
                          )}
                        >
                          {"Complexion Cream"}
                        </h4>
                      </ProductMian>
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__a1Cad)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__qyuSh
                      )}
                    >
                      {"Hair Products"}
                    </h4>
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__gdb9T)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__uJsy3)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__jImPo
                        )}
                        slot={
                          "A limited-edition, nourishing lip gel to top off your look and feel fantastic."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__mpC5O
                            )}
                          >
                            {"$24.00"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__rUOlX)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/cdae2365Eff5A961Dd838B0505A1142B656Efdf95F08C2785B59ALipsjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___1APyO
                          )}
                        >
                          {"Lip Fantastic"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__nOzgt)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__x72D
                        )}
                        slot={
                          "Treat your skin with active pore enzymes that replenish sun damaged skin."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__rqDvz
                            )}
                          >
                            {"$ 18.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__y8MZt)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/c3Cf1B72Aaa232Ba2Ab495Bd7485Efe29Cee138B5F08C2F945173Geljpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__hBzWt
                          )}
                        >
                          {"Eye Purity Gels"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__m9Ndq)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__zaLzk
                        )}
                        slot={
                          "Anti-aging complexion cream for medium to dry skin. Nourish your face with a natural vitamin burst for that perfectly balanced glow."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__tClGl
                            )}
                          >
                            {"$ 32.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___4TqYj)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/bf9Cf6844F6Febb697Cbba7Dcbbc048Abc6C1Cea5F08C2E616A7CCreamjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__xqxkm
                          )}
                        >
                          {"Complexion Cream"}
                        </h4>
                      </ProductMian>
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___4AalE)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__yxgK3
                      )}
                    >
                      {"Body Products"}
                    </h4>
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__vsuYo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__hhjDc)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__mfzXh
                        )}
                        slot={
                          "A limited-edition, nourishing lip gel to top off your look and feel fantastic."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__gDmJn
                            )}
                          >
                            {"$24.00"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__jnCw8)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/cdae2365Eff5A961Dd838B0505A1142B656Efdf95F08C2785B59ALipsjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__aCCk1
                          )}
                        >
                          {"Lip Fantastic"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__bdFg)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian___07HXz
                        )}
                        slot={
                          "Treat your skin with active pore enzymes that replenish sun damaged skin."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5___6BgwM
                            )}
                          >
                            {"$ 18.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ntErl)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/c3Cf1B72Aaa232Ba2Ab495Bd7485Efe29Cee138B5F08C2F945173Geljpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__spUlZ
                          )}
                        >
                          {"Eye Purity Gels"}
                        </h4>
                      </ProductMian>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__byCsu)}
                    >
                      <ProductMian
                        className={classNames(
                          "__wab_instance",
                          sty.productMian__kamAo
                        )}
                        slot={
                          "Anti-aging complexion cream for medium to dry skin. Nourish your face with a natural vitamin burst for that perfectly balanced glow."
                        }
                        slot2={
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__ugWnq
                            )}
                          >
                            {"$ 32.88"}
                          </h5>
                        }
                        slot3={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__mrRvw)}
                            displayHeight={
                              "320px /* plasmic-token: aNKCpOfwV38Rsi */" as const
                            }
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"100%" as const}
                            loading={"lazy" as const}
                            src={{
                              src: "/plasmic/commerce_storefront/images/bf9Cf6844F6Febb697Cbba7Dcbbc048Abc6C1Cea5F08C2E616A7CCreamjpg.jpeg",
                              fullWidth: 2400,
                              fullHeight: 3596,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___5Sw3N
                          )}
                        >
                          {"Complexion Cream"}
                        </h4>
                      </ProductMian>
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
          </div>

          <ShopingSection
            data-plasmic-name={"shopingSection"}
            data-plasmic-override={overrides.shopingSection}
            className={classNames("__wab_instance", sty.shopingSection)}
          />

          <Instagram
            data-plasmic-name={"instagram"}
            data-plasmic-override={overrides.instagram}
            className={classNames("__wab_instance", sty.instagram)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "paheHeaderMenuTextDark",
    "shopingSection",
    "instagram",
    "footer"
  ],
  paheHeaderMenuTextDark: ["paheHeaderMenuTextDark"],
  shopingSection: ["shopingSection"],
  instagram: ["instagram"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  paheHeaderMenuTextDark: typeof PaheHeaderMenuTextDark;
  shopingSection: typeof ShopingSection;
  instagram: typeof Instagram;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShop__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShop__VariantsArgs;
    args?: PlasmicShop__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShop__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicShop__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShop__ArgProps,
      internalVariantPropNames: PlasmicShop__VariantProps
    });

    return PlasmicShop__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShop";
  } else {
    func.displayName = `PlasmicShop.${nodeName}`;
  }
  return func;
}

export const PlasmicShop = Object.assign(
  // Top-level PlasmicShop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    paheHeaderMenuTextDark: makeNodeComponent("paheHeaderMenuTextDark"),
    shopingSection: makeNodeComponent("shopingSection"),
    instagram: makeNodeComponent("instagram"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicShop
    internalVariantProps: PlasmicShop__VariantProps,
    internalArgProps: PlasmicShop__ArgProps
  }
);

export default PlasmicShop;
/* prettier-ignore-end */
